### ISSUE TITLE
Edits to Chapter 1 Maintenance and Governance first paragraph

### ISSUE THREAD

**Issue by motionsuggests** [bradfrost/atomic-design#101]
Chapter 1 

Maintenance and Governance first paragraph

"... these valuable tools often can die on the vine when if they’re not given the focus they need ..."

- Place "can" before "often" 
- Remove "when" after vine 

Changes would read 

"... these valuable tools **can** often die on the ~~when~~ vine if they’re not given the focus they need ..."

**Comment by bradfrost** [comment]
Wonderful, thanks @motionsuggests! The sentence now reads:

> Even if time and money are allocated to establish style guides, these valuable tools often die on the vine if they're not given the focus they need to reach their true potential. 

Reads much better now, thanks!
