### ISSUE TITLE
Chapter 1 Lacking a clear methodology

### ISSUE THREAD

**Issue by motionsuggests** [bradfrost/atomic-design#102]
Chapter 1 under "Lacking a clear methodology" second to last sentance

"But I often feel like many pattern libraries are little more than loosely-arranged spray of modules. "

- add "a" between "than" and "loosely-arranged"

"But I often feel like many pattern libraries are little more than **a** loosely-arranged spray of modules. "

**Comment by bradfrost** [comment]
@motionsuggests Thanks for the keen eye! I changed the sentence to the following:

> But I often feel like many pattern libraries are little more than loosely-arranged sprays of modules.

Just to keep the pluralization consistent. Thanks again!
