### ISSUE TITLE
Chapter 3 spelling

### ISSUE THREAD

**Issue by BMCwebdev** [bradfrost/atomic-design#118]
I know you solidified the site a while ago (and a huge thank you for creating it) but what the heck, here's a couple spelling errors on the chapter 3 page.
 
Historically designers working in static tools have had a ~~tendancy~~ tendency to only design best...

The types of code to be highlighted in a pattern library ~~nauturally~~ naturally varies from organization...

**Comment by FullCreamMilkMan** [comment]
Hi BMCwebdev,

I'm copyediting Brad's book and I've already caught these spelling errors. The editing work will be made public quite soon. Thanks for your message, of course. It's great that everyone can chip in and help!
