### ISSUE TITLE
Link to Rizzo talk in "holy grail" section of chapter five

### ISSUE THREAD

**Issue by danoc** [bradfrost/atomic-design#119]
http://atomicdesign.bradfrost.com/chapter-5/#the-holy-grail

The section mentions Rizzou, but the only resource linked to doesn't explain the benefits of the "Component API" that Rizzou provides. I'd recommend linking to the YouTube talk or [blog post about it](http://engineering.lonelyplanet.com/2014/05/18/a-maintainable-styleguide.html).

**Comment by bradfrost** [comment]
Thanks @danoc. I haven't gotten to that section of the book yet. I'm writing it [in the open](http://bradfrost.com/blog/post/atomic-design-book/), which means there are a lot of incomplete thoughts in there. This will be covered more comprehensively when I get to it, thanks.
