### ISSUE TITLE
Another misspelled

### ISSUE THREAD

**Issue by caitlynmayers** [bradfrost/atomic-design#120]
#### Location
http://atomicdesign.bradfrost.com/chapter-5/ Done and Done Section, 1st Paragraph, 1st word

#### Description
Another is missing its o.

![screen shot 2016-04-19 at 1 51 35 pm](https://cloud.githubusercontent.com/assets/1574420/14649643/faa7c678-0635-11e6-98b7-80a4b20b2b14.png)

**Comment by bradfrost** [comment]
Hey @caitlynmayers, thanks for the keen eyes! I've addressed the issue. Really appreciate it!
