### ISSUE TITLE
Chapter 3: missing words

### ISSUE THREAD

**Issue by joebeaver89** [bradfrost/atomic-design#123]
In "Providing context with pattern lineage" section. "...patterns and templates would need retested" should be "...patterns and templates would need to be retested".

**Comment by FullCreamMilkMan** [comment]
Thanks @joebeaver89. You'll notice on the edits subdomain that I've already corrected this: http://edits.atomicdesign.bradfrost.com/chapter-3/#providing-context-with-pattern-lineage
