### ISSUE TITLE
Didn't receive my preorder

### ISSUE THREAD

**Issue by kjvdven** [bradfrost/atomic-design#128]
Contacting @bradfrost is impossible! So maybe this works.

But I didn't receive my preorder, I mailed mail receipt to Brad Frost to prove I did pay.
I expected an epub which I could read on my e-reader. But I haven't received any instructions on how to get it. Also when I think about it, I never received any mail about the book, where there any?

**Comment by bradfrost** [comment]
Hey @kjvdven,
I just shot you an email to get you sorted out. If you don't receive that email, let me know (brad@bradfrost.com) and I'll get on it right away.

**Comment by bradfrost** [comment]
@kjvdven hmmmm, I just got the following message "Delivery to the following recipient failed permanently." It looks like the email in the system for your preorder might be a broken address.

**Comment by kjvdven** [comment]
That explains a lot, you should have an email from me in your mailbox somewhere. But I can understand you get a lot of email, I could DM you my correct email on Twitter.

**Comment by bradfrost** [comment]
@kjvdven I'm afraid I don't see an email from you; feel free to DM me on Twitter and I'll get you squared away.

**Comment by kjvdven** [comment]
Oops, can't DM you on Twitter if you don't follow me. 

You can mail me on `me@krisvanderven.nl`

**Comment by bradfrost** [comment]
Email sent!

**Comment by kjvdven** [comment]
Email received, thnx!
