### ISSUE TITLE
Transform the web site into a Progressive Web Application

### ISSUE THREAD

**Issue by antoinentl** [bradfrost/atomic-design#129]
Goal: make the web book readable offline and installable.

Use SSL/TLS (HTTPS), add a Service Worker and create a manifest.

For example: [https://resilientwebdesign.com](https://resilientwebdesign.com)

**Comment by bradfrost** [comment]
@antoinentl Thanks for the suggestion! It's not going to happen (too many other things going on), but I agree it's a great idea. Damn Jeremy, raising the bar for everybody!

**Comment by antoinentl** [comment]
@bradfrost happy to know that too many other things going on :) I agree with you, it's not a priority, even more with the EPUB version.
