### ISSUE TITLE
Broken link chapter 5/Making changes to patterns

### ISSUE THREAD

**Issue by magnify** [bradfrost/atomic-design#132]
Broken link (Vanilla front-end framework) at http://atomicdesign.bradfrost.com/chapter-5/#making-changes-to-patterns.

I think this is the new link: https://github.com/vanilla-framework/vanilla-framework

**Comment by bradfrost** [comment]
@magnify Thanks! I don't actually think I'm going to update this right now because the book is now complete and it would become difficult to try to keep everything in sync. I'm going to think about how to address this and then revisit. 

Thanks so much!

**Comment by magnify** [comment]
No problem and thanks for a very inspiring book! :)

Maybe a link-manager/shortener-ish service could do the trick.
