### ISSUE TITLE
Fix horizontal overflow in pages containing a figure

### ISSUE THREAD

**Issue by Siilwyn** [bradfrost/atomic-design#133]
@bradfrost
The `figure` elements are styled to have it's width set to `100vw` causing a horizontal overflow and thus a horizontal scrollbar. This is because `100vw` doesn't include the width of the scrollbar, as per the spec:
> The viewport-percentage lengths are relative to the size of the initial containing block. When the height or width of the initial containing block is changed, they are scaled accordingly. However, when the value of overflow on the root element is auto, any scroll bars are assumed not to exist. Note that the initial containing block’s size is affected by the presence of scrollbars on the viewport.

So to fix this the `html` aka `:root` element needs to have `overflow-y: scroll` set. Wanted to PR but the way this book is build with Grunt is magic to me with no contributing docs or npm scripts. Would think `page.html` in `_layouts` needs to change something like this:
```
<!doctype html>
<html style="overflow-y:scroll;">
  {% include head.html %}
  <body>
    <main role="main">
        <div class="page-header">
          <div class="page-header-inner">
            {% if page.chapterTitle %}<h3 class="page-kicker">{{ page.chapterTitle }}</h3>{% endif %}
            <h1 class="page-title">{{ page.title }}</h1>
            {% if page.chapterSubtitle %}<p class="page-subtitle">{{ page.chapterSubtitle }}</p>{% endif %}
          </div>
        </div>
        
        <div class="text">
          {{ content }}
          
          {% if page.chapterTitle or page.title == "Foreword" %}
          {% include pagination.html %}
          {% endif %}
        </div>
        {% include banner.html %}

    </main>
    {% include footer.html %}
  </body>
</html>
```

Tested on the latest versions of Firefox.

**Comment by bradfrost** [comment]
@Siilwyn Thanks for this. I'm not able to recreate this issue on Firefox on my end. And I'm a bit confused: a vertical scrollbar is what allows you to scroll up and down the page, which is the current behavior. Are you talking about a horizontal scrollbar?

**Comment by Siilwyn** [comment]
@bradfrost whoops I'm talking about a horizontal scrollbar. The issue is present for me on Firefox and Chrome, on Linux but the OS shouldn't make a difference.

**Comment by Siilwyn** [comment]
@bradfrost I just realized you can not reproduce this because you're on MacOS!
On Windows and Linux the scrollbar takes up width causing this issue, on MacOS the scrollbar does not take up width because it lays over the page.

**Comment by Siilwyn** [comment]
Inactive issue.
