### ISSUE TITLE
Typo - Chapter 1 - Tearing up the page.

### ISSUE THREAD

**Issue by nick-novak** [bradfrost/atomic-design#26]
First paragraph, last sentence reads: 

And there’s one concept **the** keeps popping up in every conversation about how to create successful Web experiences: modularity.

It looks like it should read:

And there’s one concept **that** keeps popping up in every conversation about how to create successful Web experiences: modularity.

**Comment by bradfrost** [comment]
Thanks so much for the keen eye @nick-novak! I've fixed the typo. Appreciate it.
