### ISSUE TITLE
Reading Chapters

### ISSUE THREAD

**Issue by Lewiscowles1986** [bradfrost/atomic-design#27]
The chapters are a little lengthy for me and could do with more devices like anecdotes, quotes, and analogies. They also don't seem to lend themselves to picking up where you left off from (I'm like 1 paragraph after the first diagram on chapter 1 and I have disconnected)...

Perhaps pages do kinda suck for the web that is capable of doing so much more, but not having them, makes it hard to index, bookmark, increases loading times, bandwidth fees (in aggregates for mobile users and site-owners) etc, making me question the premise of non-paging.

Instead of

 * Book
     * Chapters[]

maybe

 * Book
     * Chapters[]
         * Pages[]

or

 * Book
     * Chapters[]
     * Pages[] *(Chapters load pages, but URL does not reflect chapter)*

even

 * Book
     * Chapters[]
     * Sections[] *(chapters would be made up of sections, each with their own heading, but the cool part is reading just a section, as it preserves context for me bookmarking a section to read later, and allows easier fine-grained editorial control.)*

or ***(best)***

 * Book
     * Chapters[]
     * Pages[]
     * Sections[] *(If you use _posts for this and adjust the permalink style, you can even benefit from previous, next functionality)*

Looking at the other issues, you seem to be using Jekyll (Have not looked that much into this, it may just be mentioned). This means you can actually create very simple rules, and devices, to help you load specific content using the liquid `where` to get a specific collection page, or post's content. This in-turn allows you to re-use content, which although not entirely obvious, is useful for any publication; so that you can re-organize content, adjust ordering etc from a high-level, and build out the content in the smallest blocks you feel comfortable with, then including using one line per section, or page or chapter.

The other benefit of this approach is that you could make your chapters pages, which use scroll-spy or similar to only load pages or sections as needed. This is a tremendous benefit, as it allows you to serve your current format, in EPIC paragraph-laden chapters, or to facilitate people like me to navigate to specifically the section I want (for bookmarking), by I would guess clicking a specific section's heading and bookmarking...

**Comment by bradfrost** [comment]
@Lewiscowles1986 thanks for the feedback and suggestions. This book is still very much a [work in progress](http://bradfrost.com/blog/post/atomic-design-book/) so I haven't committed very much time to the online reading experience. I'll keep your suggestions in mind when I tackle the design a bit more. Thanks!
