### ISSUE TITLE
Chapter 1: Word Addition/Subtraction to Sentence That Begins: "And while..."

### ISSUE THREAD

**Issue by frostyweather** [bradfrost/atomic-design#31]
Change:
>And while reading technology has come a long way – from parchment to paperback to pixels – the concept of the page holds strong to this day.

To
>While reading *that* technology has come a long way – from parchment to paperback to pixels – the concept of the page holds strong to this day.

Not supposed to start sentences with and, but since your book or more of a "spoken" thing it may be fine.

**Comment by bradfrost** [comment]
Yep, the "And" is an intentional tone of voice thing, and when I say "reading technology" I mean "the technology used to make reading happen"

Closing this one out.
