### ISSUE TITLE
Table of Contents: "2. Atomic Design Methology" [typo]

### ISSUE THREAD

**Issue by ashleyv** [bradfrost/atomic-design#56]
On the Chapter 2 header in the table of contents, "Methology" should be "Methodology"
![atomic design - toc issue](https://cloud.githubusercontent.com/assets/3210496/9233057/92f83d6e-40f6-11e5-9b88-5549252e3356.png)

**Comment by bradfrost** [comment]
@ashleyv Oh jeez that's embarrassing! Thanks for the heads-up. Should be fixed now.
