### ISSUE TITLE
Chapter 1: Use of hypen and en-dash

### ISSUE THREAD

**Issue by vishallama** [bradfrost/atomic-design#64]
In the sentence

> How can we present primary navigation-**typically displayed as a horizontal list on large screens**–in a thoughtful way on smaller screens?

it looks like the highlighted text is enclosed by a hyphen and an en-dash. Perhaps, they should either be enclosed by a couple of en-dashes, which should have spaces around them, or they should be enclosed by a couple of em-dashes, which not have any spaces around them.

More info on the use of hyphens and dashes can be found [here](http://www.dashhyphen.com/).

**Comment by ivan-kolmychek** [comment]
Just stumbled upon this in that exact place.

It took me three readings and one "inspect element" to finaly understand that it's a dash and it does not link two words, but instead marks the "sub-sentence" limits. :)

**Comment by bradfrost** [comment]
Thanks @vishallama and @ivan-kolmychek. I've addressed this issue in this specific place, and will be going through to tighten up a lot of the grammar rules throughout the book. I appreciate it!
